In [2]:
import numpy as np

In [7]:
#Array function turns lists into arrays.
my_matrix = [[1,2,3], [4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
#equivelent to python range function
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [34]:
#After creating a single list, we can use reshape to reorganize them into an array, by specifying hte dimensions.
arr = np.arange(0,25)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
#creating an array of zeroes. retruns with a period, because it is a floating number.
#First input is "shape" of the array. One number will give us a single row, with n columns.
#np.ones() returns similarly, with ones.
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
#The shape can be manipulated though to also include several rows.
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [3]:
#Return evenly spaced numbers over an expressed interval.
#Going from 0 - 10, return two evenly spaced intervals.
##we need 3 to express two intervals, to include the endpoint
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [18]:
#numpy identity matrix.
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
#####Using Random Data#####

In [20]:
#create an array of the given shape, and pipulate it with random samples from a uniform distribution
np.random.rand(1)
#returns a single random number between 0 and 1.

array([0.3065378])

In [21]:
np.random.rand(5,6)
#retunrs a random number between 0 and 1, for a 5X6 matrix.

array([[0.98905145, 0.90737962, 0.08318698, 0.98442069, 0.73350399,
        0.70060104],
       [0.6487253 , 0.06593973, 0.21015714, 0.08786101, 0.33063615,
        0.4517917 ],
       [0.33278647, 0.69457155, 0.92518477, 0.68319134, 0.93689631,
        0.34358328],
       [0.43291002, 0.8609657 , 0.90902626, 0.76503436, 0.97935174,
        0.73330806],
       [0.81925721, 0.7306165 , 0.67551925, 0.77070562, 0.3235685 ,
        0.93941854]])

In [22]:
#returning samles from a normal distribution
np.random.randn(2,3)

array([[ 0.97985657,  0.57912717,  0.43912589],
       [-0.68142016,  0.35032461,  0.08200602]])

In [28]:
#Random integers
np.random.randint(0,101,(5,5))

array([[91, 67, 68, 92, 41],
       [36, 48, 16, 11, 55],
       [83, 65,  6, 64, 12],
       [14, 84,  2, 90, 58],
       [39, 61, 40, 29, 35]])

In [29]:
#Seed allows us to set a particular set of random numbers. The seed number is purely arbitrary, and just allows us to keep track of the random distribution. When we then choose 4 random numbers, it will only return for us those 4 seeded numbers.
#The main advantage of this is to repeat the results of random distributions, to be able to test them differently.
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [37]:
ranarr= np.random.randint(0,101,10)
ranarr

array([ 1, 87, 29, 37,  1, 63, 59, 20, 32, 75])

In [38]:
ranarr.max()

87

In [39]:
ranarr.min()

1

In [41]:
#return the index of the max (or min)
ranarr.argmax()

1