In [3]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
#With numpy, we can directly broadcast the values of the array (list), with slicing. In python, lists do not have this capability
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [17]:
#slciing will point back to the original array. Even if we set a new variable, the broadcasted slice will also broadcast onto the original array. 
arr = np.arange(0,11)
print(arr)
slice_of_arr = arr[0:5]
print(slice_of_arr)
slice_of_arr[:] = 99
print(slice_of_arr)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4]
[99 99 99 99 99]
[99 99 99 99 99  5  6  7  8  9 10]


In [18]:
#To only affect the new variable, we have to make a copy.
arr = np.arange(0,11)
arr_copy = arr.copy()

In [34]:
##### INDEXING #####
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,50]])
print(arr_2d)
print(arr_2d.shape)

[[ 5 10 15]
 [20 25 30]
 [35 40 50]]
(3, 3)


In [26]:
#Grabing a Row
arr_2d[2]

array([35, 40, 50])

In [27]:
#grabbing a cell
print(arr_2d[1][1])
#Or, commonly
print(arr_2d[1,1])

25
25


In [36]:
#We can also use this while splicing. If we want the top middle and right--
print(arr_2d[0][1:])
print(arr_2d[:2, 1:])

array([[10, 15],
       [25, 30]])

In [37]:
### CONDITIONAL SELECTION
arr = np.arange(0,11)
print(arr)
bool_arr = arr >4
print(bool_arr)

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [41]:
#We can use this boolean array to pass it in to arr, to return the index locations of the Trues
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [42]:
#Much more simply, we can pass the conditional into the reference
#This is very common.
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])