In [2]:
import numpy as np
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#If adding to an array, it will add to each element in the array
print(arr + 5)
print(arr -2)

[ 5  6  7  8  9 10 11 12 13 14]
[-2 -1  0  1  2  3  4  5  6  7]


In [6]:
#This works for every arithmetic function
print(arr*arr)
print(arr-arr)


SyntaxError: invalid syntax (<ipython-input-6-5ff1fd76489a>, line 4)

In [10]:
#If dividing, and there is a 0 in the array (that tries to divide by itself), numpy will turn the zero into "nan" or infinity (if dividing 1/0)
print(arr/arr)
print(1/arr)

[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]
<ipython-input-10-a54721d5a36b>:2: RuntimeWarning: invalid value encountered in true_divide
  print(arr/arr)
<ipython-input-10-a54721d5a36b>:3: RuntimeWarning: divide by zero encountered in true_divide
  print(1/arr)


In [12]:
#numpy also has other mathmatical functions, such as numpy.log, or numpy.sin
arr.sum()

45

In [14]:
arr.mean()

4.5

In [16]:
arr.var()
arr.std()

2.8722813232690143

In [22]:
#We can also solve for different aspects of the array, such as rows or columns
arr2d = np.arange(0,25).reshape(5,5)


In [23]:
#To get the sums of each column:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [24]:
#To get the sums of each row
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])