In [2]:
import numpy as np
#All questions from https://www.w3resource.com/python-exercises/numpy/basic/index.php#EDITOR

In [ ]:
#2 get help for the add function

print(np.info(np.add))

In [11]:
#3. Write a NumPy program to test whether none of the elements of a given array is zero


zeros = np.ones(15)
zeros = np.append(zeros, 0)
print(zeros)
np.all(zeros)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]


False

In [14]:
#4. Write a NumPy program to test whether any of the elements of a given array is non-zero
zeros = np.ones(15)
zeros = np.append(zeros, 0)
np.any(zeros)

True

In [17]:
#5 Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number)
list = np.array([1,0, np.nan, np.inf])
np.isfinite(list)

array([ True,  True, False, False])

In [19]:
#6 Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.
print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))
print(np.allclose([1.0, np.nan], [1.0, np.nan]))
print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True))


False
True
False
True


In [27]:
#13 Write a NumPy program to create an array of 10 zeros
np.array([0]*10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
#14 Write a NumPy program to create an array of the integers from 30 to70. Just the evens?
print(np.arange(30,71))
print(np.arange(30,71,2))

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [30]:
#16 Write a NumPy program to create a 3x3 identity matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [60]:
#17 Write a NumPy program to generate a random number between 0 and 1
np.random.rand()

0.1340743069146274

In [61]:
#18 Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution
np.random.randn(15)

array([ 0.65919208,  1.25833682,  0.53752885, -0.9864112 ,  1.88758105,
       -0.24956936, -1.70103411,  0.1628166 , -0.27201643,  0.34737733,
       -0.77403791, -0.69645676, -2.41964227,  2.4578862 ,  0.77009562])

In [63]:
#19 Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.
vector = np.arange(15, 55)
vector[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53])

In [71]:
#20 Write a NumPy program to create a 3X4 array using and iterate over it
array = np.arange(0,12).reshape(3,4)
for x in np.nditer(array):
    print(x, end = " ")

0 1 2 3 4 5 6 7 8 9 10 11 

In [73]:
#21. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50
np.linspace(5, 50, 10)

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [82]:
#22 Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

vector = np.arange(0,21)
vector[(vector >= 9) & (vector <=15)]*= -1
print(vector)


[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [85]:
#24 multiply two vectors together
ara= np.array([1,2,3,4])
arb = np.array([2])
ara*arb


array([2, 4, 6, 8])

In [87]:
# Create a 3X4 matric filled with values from 10 to 21. What is its shape?
x= np.arange(10,22).reshape(3,4)
print(x)
print(x.shape)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
(3, 4)


In [96]:
array = np.ones((10,10))
array[1:-1, 1:-1] = 0

print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [102]:
#29 Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [113]:
#30 Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal. 
x = np.zeros((4,4))
x[::2, 1::2] = 1
x[1::2, ::2] = 1
x

array([[0., 1., 0., 1.],
       [0., 0., 0., 0.],
       [0., 1., 0., 1.],
       [0., 0., 0., 0.]])

In [125]:
#31 Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.
x = np.arange(0, 25).reshape(5,5)
print(x)
print('col: ', np.sum(x, axis = 0))
print('row: ', np.sum(x, axis = 1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
col:  [50 55 60 65 70]
row:  [ 10  35  60  85 110]


In [156]:
#34 Write a NumPy program to add a vector to each row of a given matrix
x = np.arange(0,25).reshape(5,5)
y = np.array([1]*5)
result = np.empty_like(x)
for i in range(5):
    result[i, :] = x[i, :] + y
print(result)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [162]:
#39 Write a NumPy program to convert a given list into an array, then again convert it into a list. Check initial list and final list are equal or not.
list = [1,2,3,4,5,6,7,8,9]
x = np.array(list).reshape(3,3)
x.tolist()

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]